### 1. Registrar Usuário (Se precisar de outro, mude o e-mail)
POST http://localhost:5219/api/auth/register
Content-Type: application/json

{
  "name": "Ana",
  "email": "ana@dams.com",
  "password": "SenhaSegura123!",
  "role": "Admin"
}

### 2. Login para obter o Token
POST http://localhost:5219/api/auth/login
Content-Type: application/json

{
  "email": "ana@dams.com",
  "password": "SenhaSegura123!"
}