@DAMS.Api_HostAddress = http://localhost:5219

### 1. Registrar Usuário
POST {{DAMS.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "name": "Ana Carolina",
  "email": "ana@dams.com",
  "password": "SUA_SENHA_AQUI",
  "role": "Admin"
}

### 2. Login
POST {{DAMS.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "ana@dams.com",
  "password": "SUA_SENHA_AQUI"
}

### 3. Get Admissions
GET {{DAMS.Api_HostAddress}}/api/admissions
Accept: application/json
Authorization: Bearer <COLE_SEU_TOKEN_AQUI>

### 4. Get Admission by Id
GET {{DAMS.Api_HostAddress}}/api/admissions/00000000-0000-0000-0000-000000000000
Accept: application/json
Authorization: Bearer <COLE_SEU_TOKEN_AQUI>